Add additional `Model` convenience methods
neo4j/graph-data-science-client pull request #119
Opened 2022-06-02 11:26 UTC by adamnsch

2022-06-02 12:33 UTC, Mats-SX requested changes
I think we should discuss the name of `pipeline` and what other convenience methods we can add. Maybe we want to call it `pipeline_steps` for example.

2022-06-02 12:33 UTC, Mats-SX commented on changelog/1.1.0.md
> +* Added new convenience method `NCModel.classes` to list the that was used to train a node classification model.
```suggestion
* Added new convenience method `NCModel.classes` to list the classes that were used to train a node classification model.
```

2022-06-02 12:33 UTC, Mats-SX commented on graphdatascience/model/pipeline_model.py
> +        return pandas.Series(self._list_info()["modelInfo"][0]["pipeline"])
Maybe we wanna call this `pipeline_steps`?

2022-12-14 13:56 UTC, FlorentinD approved these changes
LGTM

Some smaller remarks only ;)

2022-12-14 13:56 UTC, FlorentinD commented on graphdatascience/pipeline/training_pipeline.py
> +M = TypeVar("M", bound=PipelineModel, covariant=True)
maybe we find a better name than a single letter?

2022-12-15 07:57 UTC, Mats-SX commented on doc/modules/ROOT/pages/pipelines.adoc
> +pipe = gds.nc_pipe("my-pipe")
Yes it is on purpose. We are opting for maximum convenience to really remove any obstacle from users that want to use pipelines.

2022-12-15 07:57 UTC, Mats-SX commented on graphdatascience/model/link_prediction_model.py
> +@dataclass(frozen=True, repr=True)
Maybe it is, but I thought it was clearer to set it explicitly.

2022-12-15 07:59 UTC, Mats-SX commented on doc/modules/ROOT/pages/pipelines.adoc
> +pipe = gds.nr_pipe("my-pipe")
Yeah it is potentially risky but I think we can take a small risk here on the client -- a user would still know about the tier from the Cypher API and the manual.

2022-12-15 08:03 UTC, Mats-SX commented on graphdatascience/model/link_prediction_model.py
> +        steps: List[Dict[str, Any]] = self._list_info()["modelInfo"][0]["pipeline"]["featureSteps"]
That's pre-existing. The reason is because `_list_info()` is returning directly from `run_cypher()` which always is a `DataFrame`.

2022-12-15 08:03 UTC, Mats-SX commented on graphdatascience/model/link_prediction_model.py
> +        steps: List[Dict[str, Any]] = self._list_info()["modelInfo"][0]["pipeline"]["featureSteps"]
That's pre-existing. The reason is because `_list_info()` is returning directly from `run_cypher()` which always is a `DataFrame`.

2022-12-15 08:03 UTC, Mats-SX commented on graphdatascience/model/link_prediction_model.py
> +        steps: List[Dict[str, Any]] = self._list_info()["modelInfo"][0]["pipeline"]["featureSteps"]
(wth, I accidentally reported my own comment and wrote it twice 😅 )

2022-12-15 08:04 UTC, Mats-SX commented on graphdatascience/model/model.py
> +        return Series(self._list_info()["modelInfo"].squeeze())
You could be correct, since there's only ever 1 row coming out of `_list_info()` -- but not for this PR I think.

2022-12-15 08:06 UTC, Mats-SX commented on graphdatascience/model/pipeline_model.py
> +class EvaluationScores(Dict[str, float]):
Do you think it's too risky to replicate this client-side? I figured that this metric triple would remain stable, but yes it is a bit of a bet.

2022-12-15 08:08 UTC, Mats-SX commented on graphdatascience/model/pipeline_model.py
> +class EvaluationScores(Dict[str, float]):
I kinda prefer `EvaluationScores` to `ModelStats` so maybe a refactoring server-side would be my preference. What do you think?

It's not part of the API, I believe. It's an anonymous map/dict in a list mapped to some metric name.

2022-12-15 08:26 UTC, FlorentinD commented on graphdatascience/model/model.py
> +        return Series(self._list_info()["modelInfo"].squeeze())
True, maybe we can card it? (seems like a minor adjustment but I agree not on this PR)

2022-12-15 08:28 UTC, FlorentinD commented on graphdatascience/model/pipeline_model.py
> +class EvaluationScores(Dict[str, float]):
I also like `EvaluationScores` more

2022-12-15 08:29 UTC, FlorentinD commented on graphdatascience/model/pipeline_model.py
> +class EvaluationScores(Dict[str, float]):
Its not part of the external API but for our team it would be better to use the same names IMO

2022-12-15 12:55 UTC, Mats-SX commented on graphdatascience/model/pipeline_model.py
> +class EvaluationScores(Dict[str, float]):
I will push a commit to master

2022-12-15 13:10 UTC, Mats-SX commented on graphdatascience/model/model.py
> +        return Series(self._list_info()["modelInfo"].squeeze())
OK added to card.

2022-12-15 13:44 UTC, merged