Add new graph ops endpoints
neo4j/graph-data-science-client pull request #130
Opened 2022-07-13 13:40 UTC by soerenreichardt

2022-07-13 13:43 UTC, soerenreichardt commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update the python client](https://trello.com/c/YMHV3KTF/6439-update-the-python-client)

2022-07-14 08:23 UTC, adamnsch requested changes
Nice work :) Just have some minor comments

2022-07-14 08:31 UTC, adamnsch commented on changelog/1.3.0.md
> +* Add new graph operations endpoints in gds >2.2.0
```suggestion
* Add support for new graph catalog endpoints in GDS >= 2.2.0.
```

2022-07-14 11:49 UTC, soerenreichardt commented on graphdatascience/graph/graph_ops_runner.py
> +from typing import Any, Callable, Dict, List, Union
I agree, but I struggle a bit with finding a good name. Maybe `graph_entity_ops_runner`?

2022-07-14 11:52 UTC, soerenreichardt commented on graphdatascience/tests/unit/test_graph_ops.py
> +    runner.set__mock_result(result_df)
I copied this from the test above, but I can remove it in both cases

2022-07-14 12:26 UTC, soerenreichardt commented on graphdatascience/tests/integration/test_graph_ops.py
> +        result = gds_without_arrow.graph.streamNodeProperty(G, "x", concurrency=2)
I extracted individual tests for these now

2022-07-14 15:24 UTC, adamnsch approved these changes
Very nice work :) Will be nice in when we can remove support for the old API

2022-07-18 16:47 UTC, FlorentinD commented on graphdatascience/graph/graph_entity_ops_runner.py
> +    def write(self, G: Graph, node_properties: List[str], node_labels: Strings = ["*"], **config: Any) -> Series:
@soerenreichardt 
MyPy complains here `Returning Any from function declared to return "Series"`

Running `./scripts/checkstyle`.

2022-07-18 16:50 UTC, FlorentinD commented on graphdatascience/graph/graph_entity_ops_runner.py
> +    def write(self, G: Graph, node_properties: List[str], node_labels: Strings = ["*"], **config: Any) -> Series:
similar to previous call-sites we ignore the type warning here, as we know that write/drop will only return a single row

2022-07-19 08:26 UTC, adamnsch commented on graphdatascience/graph/graph_entity_ops_runner.py
> +    def drop(self, G: Graph, node_properties: List[str], **config: Any) -> DataFrame:
done

2022-07-19 08:27 UTC, adamnsch approved these changes

2022-07-19 09:19 UTC, merged