Add endpoints for graph property procs
neo4j/graph-data-science-client pull request #137
Opened 2022-07-25 08:00 UTC by soerenreichardt

2022-07-25 08:02 UTC, soerenreichardt commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Arrow] Graph Properties continued](https://trello.com/c/xjmRlN7M/6052-arrow-graph-properties-continued)

2022-07-27 11:21 UTC, jjaderberg requested changes
As far as I understand it this change is good but the tests are a bit broken

2022-07-27 11:21 UTC, jjaderberg commented on graphdatascience/graph/graph_entity_ops_runner.py
> +class GraphElementPropertyRunner(GraphEntityOpsBaseRunner):
is element and entity the same thing here?
its a small detail but maybe we could use the same term (if indeed it refers to the same thing)

2022-07-27 11:21 UTC, jjaderberg commented on graphdatascience/tests/unit/test_graph_ops.py
> +    assert runner.last_params() == {"graph_name": "g", "graph_property": "prop"}
missing the config here?

2022-07-27 11:21 UTC, jjaderberg commented on graphdatascience/tests/unit/test_graph_ops.py
> +    gds.alpha.graph.graphProperty.stream(G, "prop")
```suggestion
    gds.alpha.graph.graphProperty.drop(G, "prop")
```

2022-07-27 13:21 UTC, merged