Support ToUndirected
neo4j/graph-data-science-client pull request #235
Opened 2022-12-20 11:48 UTC by DarthMax

Thank you for your contribution to the Graph Data Science Client project.

Before submitting this PR, please read [Contributing to the Neo4j Ecosystem](https://github.com/neo4j/graph-data-science-client/blob/main/CONTRIBUTING.md). 

Make sure:
- [ ] You signed the [Neo4j CLA](https://neo4j.com/developer/cla/#sign-cla) (Contributor License Agreement) so that we are allowed to ship your code in our library
- [ ] Your contribution is covered by tests

2022-12-20 16:01 UTC, Mats-SX requested changes
The blocking comment is for the test.

2022-12-20 16:01 UTC, Mats-SX commented on changelog.md
> +* Added a new method `gds.graph.relationships.to_undirected` to turn a directed relationship type to an undirected, when using GDS >= 2.3.0
```suggestion
* Added a new endpoint `gds.beta.graph.relationships.to_undirected` to turn a directed relationship type to an undirected, when using GDS >= 2.3.0
```

2022-12-20 16:01 UTC, Mats-SX approved these changes

2022-12-21 09:36 UTC, DarthMax commented on graphdatascience/graph/graph_entity_ops_runner.py
> +            "relationshipType": relationship_type,
Yeah unfortunately it does only work with Pyton >= 3.9

2022-12-21 09:49 UTC, Mats-SX commented on graphdatascience/graph/graph_entity_ops_runner.py
> +            "relationshipType": relationship_type,
😢

2022-12-21 09:50 UTC, Mats-SX commented on changelog.md
> +* Added a new method `gds.graph.relationships.to_undirected` to turn a directed relationship type to an undirected, when using GDS >= 2.3.0
```suggestion
* Added a new endpoint for the new procedure `gds.beta.graph.relationships.toUndirected` in GDS 2.3
```

2022-12-21 09:58 UTC, merged