Fix ogbl-wikikg2 loader
neo4j/graph-data-science-client pull request #363
Opened 2023-05-04 12:58 UTC by brs96

Thank you for your contribution to the Graph Data Science Client project.

Before submitting this PR, please read [Contributing to the Neo4j Ecosystem](https://github.com/neo4j/graph-data-science-client/blob/main/CONTRIBUTING.md). 

Make sure:
- [ ] You signed the [Neo4j CLA](https://neo4j.com/developer/cla/#sign-cla) (Contributor License Agreement) so that we are allowed to ship your code in our library
- [ ] Your contribution is covered by tests

2023-05-09 10:55 UTC, brs96 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Cypher aggregation OGB graph fails with IllegalArgumentException: The node has to be either a NODE or an INTEGER, but got Double](https://trello.com/c/gDoYb8By/8122-cypher-aggregation-ogb-graph-fails-with-illegalargumentexception-the-node-has-to-be-either-a-node-or-an-integer-but-got-double)

2023-05-10 08:03 UTC, adamnsch requested changes
Nice work :) Let me know if you want to discuss any of the comments

2023-05-10 08:03 UTC, adamnsch commented on graphdatascience/graph/ogb_loader.py
> +    name: str
We don't need this attribute for the other Dataset protocols right?

2023-05-10 08:03 UTC, adamnsch commented on graphdatascience/tests/integration/test_ogb_loader.py
> +def test_graph_load_ogbl_wikikg2(gds: GraphDataScience) -> None:
There are several more asserts I would like to have in this test (see `test_graph_load_ogbn_arxiv above`)

2023-05-10 08:03 UTC, adamnsch commented on graphdatascience/tests/integration/test_ogb_loader.py
> +    # 535 train rels
?

2023-05-10 14:27 UTC, adamnsch approved these changes

2023-05-10 15:00 UTC, merged