Adding Community detection example jupyter notebook (continued)
neo4j/graph-data-science-client pull request #375
Opened 2023-05-17 08:57 UTC by FlorentinD

based on #373.

Hopefully CI runs here now

2023-05-17 08:59 UTC, FlorentinD commented
@kedarghule the mentioned PR.

Also asking @nvitucci to get some feedback on the wording :)

2023-05-23 13:19 UTC, FlorentinD commented
Great idea to add more notebooks as you keep learning! 

It was just a typo in the code which I fixed now.

Also, added you as a collaborator to my fork.

As some context, CI did not run on your PR as only internal contributor can kick off CI. This is helpful to avoid malicious people to run f.i. mining code on a PR. I will bring it up in our team to see what we can improve in the process. IMO its fine that only we care about the CI output and let you know, but it should be possible to kick off CI from your original PR

2023-05-23 14:58 UTC, kedarghule commented
> Great idea to add more notebooks as you keep learning!
> 
> It was just a typo in the code which I fixed now.
> 
> Also, added you as a collaborator to my fork.
> 
> As some context, CI did not run on your PR as only internal contributor can kick off CI. This is helpful to avoid malicious people to run f.i. mining code on a PR. I will bring it up in our team to see what we can improve in the process. IMO its fine that only we care about the CI output and let you know, but it should be possible to kick off CI from your original PR

Hi thanks for adding me to your fork :) I'll use it for future notebooks I intend to make :D

2023-05-24 10:32 UTC, nvitucci requested changes
Thank you very much @kedarghule! I've just added a few small suggestions on the style.

2023-05-24 10:32 UTC, nvitucci commented on examples/community-detection.ipynb
> +    "# get unique nodes for each column\n",
```suggestion
    "# Get unique nodes for each column\n",
```

2023-05-24 10:32 UTC, nvitucci commented on examples/community-detection.ipynb
> +    "# get unique nodes for both columns\n",
```suggestion
    "# Get unique nodes for both columns\n",
```

2023-05-24 10:32 UTC, nvitucci commented on examples/community-detection.ipynb
> +    "# create new dataframe with distinct nodes\n",
```suggestion
    "# Create new dataframe with distinct nodes\n",
```

2023-05-24 10:32 UTC, nvitucci commented on examples/community-detection.ipynb
> +    "every other node in the graph dataset (subgraphs in it may not connected to each other at all). Hence, we \n",
```suggestion
    "every other node in the graph dataset (subgraphs in it may not be connected to each other at all). Hence, we \n",
```

2023-05-24 10:32 UTC, nvitucci commented on examples/community-detection.ipynb
> +    "We use the [Weakly Connected Components](https://neo4j.com/docs/graph-data-science/2.4-preview/algorithms/wcc/) algorithm to find sets of connected nodes and assign each set a component id."
```suggestion
    "We use the [Weakly Connected Components](https://neo4j.com/docs/graph-data-science/current/algorithms/wcc/) algorithm to find sets of connected nodes and assign each set a component ID."
```

2023-05-24 10:32 UTC, nvitucci commented on examples/community-detection.ipynb
> +    "\"\"\"\n",
```suggestion
    "    \"\"\"\n",
```

2023-05-24 10:32 UTC, nvitucci commented on examples/community-detection.ipynb
> +    "Largest_CC, _ = gds.beta.graph.project.subgraph(\n",
I'd suggest to rename `Largest_CC` to `largest_component_graph` or `lcc_graph`.

2023-05-24 10:32 UTC, nvitucci commented on examples/community-detection.ipynb
> +    "* Inspect the produced communities using [Bloom](https://neo4j.com/docs/bloom-user-guide/current/). Tip you can use a rule-based styling based on the community property.\n",
```suggestion
    "* Inspect the produced communities using [Bloom](https://neo4j.com/docs/bloom-user-guide/current/). You can use rule-based styling based on the community property.\n",
```

2023-05-24 11:45 UTC, FlorentinD commented
@nvitucci Thanks for the suggestions. (@kedarghule I took the liberty to apply the comments directly :) )

2023-05-24 12:46 UTC, kedarghule commented
> @nvitucci Thanks for the suggestions. (@kedarghule I took the liberty to apply the comments directly :) )

Thank you for the suggestions @nvitucci and thanks for applying them before I woke up haha @FlorentinD :D
A check still seems to be failing. Is there anything I can do about it?

2023-05-24 17:09 UTC, merged

2023-05-24 20:07 UTC, kedarghule commented
> I rebased on main, the latest failure was not related to us :)

Thank you :D

2023-05-25 07:09 UTC, FlorentinD commented
Congratulations on getting your first PR merged @kedarghule :partying_face: