Make TTL configurable
neo4j/graph-data-science-client pull request #724
Opened 2024-08-26 16:00 UTC by DarthMax

- **update gitignore**
- **Add support to skip notebooks for AuraDS-based sessions**
- **Condional check on local db for running notebooks**
- **assume encrypted connection between database and session (for arrow)**
- **add example for self-managed database**
- **Split tox target for sessions against self-managed db**
- **Run local tests unencrypted**
- **Set db -> session traffic locally to unencrypted**
- **Improve wording in notebook**
- **Document sessions against self-managed (manual)**
- **Improve reference docs**
- **AuraDbQueryRunner**
- **Expose ttl configuration to the user**

2024-08-26 16:01 UTC, DarthMax commented
![](https://github.trello.services/images/mini-trello-icon.png) [[🍓] Enable client to create sessions against self-managed dbms](https://trello.com/c/8FRF05Jk/9295-%F0%9F%8D%93-enable-client-to-create-sessions-against-self-managed-dbms)

2024-08-27 13:16 UTC, FlorentinD approved these changes
Looks good.

Main suggestion is to add it to the notebooks as well for user visibility (and CI testing)

2024-08-27 13:16 UTC, FlorentinD commented on doc/modules/ROOT/pages/gds-session.adoc
> +This optional parameter specifies the time-to-live of the session. The session will be automatically deleted after the TTL has expired after the last user activity.
```suggestion
This optional parameter specifies the time-to-live of the session. The session will be automatically deleted if the session was unused for the provided duration.
```

2024-08-27 13:16 UTC, FlorentinD commented on doc/modules/ROOT/pages/gds-session.adoc
> +    ttl=timedelta(hours=5),
how about we also add it to the notebook?

2024-08-27 13:16 UTC, FlorentinD commented on graphdatascience/session/aura_api.py
> +        self, name: str, pwd: str, memory: SessionMemoryValue, ttl: Optional[str], cloud_location: CloudLocation
similar to memory, we could pass the ttl as the typed timedelta here

2024-08-27 13:16 UTC, FlorentinD commented on graphdatascience/session/dedicated_sessions.py
> +            # TODO check cloud location?
will be covered in https://trello.com/c/8oUk8poI

2024-08-27 13:16 UTC, FlorentinD commented on graphdatascience/session/gds_sessions.py
> +        return self._impl.get_or_create(session_name, memory, db_connection, ttl=ttl, cloud_location=cloud_location)
should throw if its used for AuraDS based sessions

2024-08-27 13:42 UTC, Mats-SX requested changes
I think we should define what activities refresh the TTL. But other than that, looks very good.

2024-08-27 18:46 UTC, DarthMax commented on doc/modules/ROOT/pages/gds-session.adoc
> +    ttl=timedelta(hours=5),
We are currently not describing the example at all. I think that if we add this line, we would also have to describe the rest of the parameters, which would be a duplication of the description above.

2024-08-28 12:23 UTC, merged